### ISSUE TITLE
Support: Oracle API Gateway as environment list item

### ISSUE THREAD

**Issue by juliajuju93** [Azure/api-center#10]
# What are you trying to achieve?

APIM and APIC customer is requesting Oracle API Gateway support - listed as an environment list item:
![image](https://github.com/Azure/api-center-preview/assets/42241691/5f63ec16-5b5c-4ba5-91ff-e68dcc0b1576)

**Comment by pierceboggan** [comment]
@juliajuju93 - Thanks for the bug report! You can now specify any **Environment** server type you wish by typing directly in the field: 
![image](https://github.com/Azure/api-center/assets/1091304/7a581ff3-8e65-4eb4-9d26-bdf15ebdabc6)

After creating the environment, the type is updated to reflect Oracle API Gateway as requested:
![image](https://github.com/Azure/api-center/assets/1091304/55631768-5c8c-4c99-918d-c054529abc95)
