### ISSUE TITLE
Importing multiple APIs

### ISSUE THREAD

**Issue by TIGHEDEV** [Azure/api-center#11]
# What are you trying to achieve?

Will we be able to import more than one API at a time? 

# Proposed solution

# Alternative solutions

# Additional context

**Comment by juliajuju93** [comment]
@TIGHEDEV:
Thanks for your feedback.

Have you seen our latest CLI release where you can use CLI to import APIs: https://learn.microsoft.com/en-us/azure/api-center/manage-apis-azure-cli 
Or you can use our newest APIM import functionality: https://learn.microsoft.com/en-us/azure/api-center/import-api-management-apis?tabs=portal

Please let me know if this helps and works for you!

Also any new feedback is highly welcome!
