### ISSUE TITLE
Ability to select pre-existing APIs from API Management

### ISSUE THREAD

**Issue by TIGHEDEV** [Azure/api-center#12]
# What are you trying to achieve?

Looking to be able to import APIs that already exist in API Management automatically into API Center. This would mean that there is less likelihood of mistakes being made in API Center as we can use the information already in API Management.

# Proposed solution

Functionality, like a drop down box where we can select existing APIs rather than having to type out details for every API.

# Alternative solutions

# Additional context

**Comment by jharbieh-microsoft** [comment]
Agreed! At the moment it feels like all is manual tracking ... data entry. In most cases, where customers have APIM deployed, we'd love it if we can import in all that information into the API Center vs. manually enter that data. Thanks team!

**Comment by pierceboggan** [comment]
@TIGHEDEV , @jharbieh-microsoft - This functionality is now available in the Azure CLI with our Import from API Management command. More documentation is available here: https://learn.microsoft.com/en-us/azure/api-center/import-api-management-apis?tabs=portal

Give it a try and let us know what you think!
