### ISSUE TITLE
Help example for `az apic api update --help` missing required property (workspace)

### ISSUE THREAD

**Issue by neilpeterson** [Azure/api-center#21]
The example provided here is missing the workspace property, which seems to be required. Total nit but would be helpful to update the example.

```
PS > az apic api update --help

Examples
    Update API
        az apic api update -g contoso-resources -s contoso --name echo-api --summary "Basic REST API
        service"
```

Without specifying the workspace, the following is thrown.

```
InvalidArgumentValue: Missing required field: -w
```

**Comment by pierceboggan** [comment]
@neilpeterson - Thanks for the report! This should be fixed in our most recent Azure CLI extension release 1.0.0b5. If you're still hitting versions on this issue, feel free to reopen this issue and tag me directly.
