### ISSUE TITLE
Ability to edit API definitions in Azure portal

### ISSUE THREAD

**Issue by justinyoo** [Azure/api-center#26]
# Description

When I looked at the `edit` button on the API definition screen, I was expecting to modify the API definition.
 
![image](https://github.com/Azure/api-center-preview/assets/1538528/3b4f515f-df37-4fbe-a5e6-73dec7f8187e)

However, it's not. I am only able to update the tile and description, not the API definition.

![image](https://github.com/Azure/api-center-preview/assets/1538528/6f63e09c-88e2-4451-bbb8-2db0b8440f2b)

We should be able to update the API definition directly on the portal. The only way to update the API definition is to use either Azure CLI or upload a file to the portal.

# Expected behavior

- To update title and description, as well as the API definition

# Actual behavior

- To update title and description

**Comment by juliajuju93** [comment]
Thanks for the feedback.
API Center is an inventory solution to store and manage your organizational APIs. Our intention is not to provide a tool where customers can easily edit and edit their API specs. For this we recommend using tools like VS Code.

Please let me know if you have any further questions on this.

**Comment by juliajuju93** [comment]
Closing
