### ISSUE TITLE
Registration error when the summary section of an OpenAPI definition doc is longer than 200 characters

### ISSUE THREAD

**Issue by justinyoo** [Azure/api-center#28]
# Description

- `az`: `2.57.0`
- `az apic-extension`: `1.0.0b4`
- OS: Windows 11

![image](https://github.com/Azure/api-center-preview/assets/1538528/a43976a9-6505-47e4-b2ea-97751b20ff02)

I use the Pet Store sample from https://editor.swagger.io in JSON format. However, it throws an error while registering through Azure CLI, because it has the description whose length is longer than 200 characters.

# Reproduction steps

1. Download the Pet Store sample OpenAPI doc from https://editor.swagger.io in JSON format.
1. Register the OpenAPI doc through Azure CLI like:

    ```bash
    az apic api register -g "my-resource-group" -s "my-api-center" --api-location "./pet-store.json"
    ```

1. Get the error like the screenshot above.

# Expected behavior

- It should be registered without an error.

# Actual behavior

- It throws an error message like the screenshot above.

# Additional context

- Registering the same OpenAPI doc through Azure Portal is fine.
- It seems that the CLI tries to map the description of the OpenAPI doc to the summary of APIC, instead of the description.

**Comment by pierceboggan** [comment]
@justinyoo - I wasn't able to reproduce this on our latest Azure CLI version. Reached out to confirm if it's fixed for you.

**Comment by pierceboggan** [comment]
Confirmed with @justinyoo this is now resolved! Thanks for your report. :)
