### ISSUE TITLE
Log out button in API Center Portal

### ISSUE THREAD

**Issue by georgeollis** [Azure/api-center#35]
Is it possible to add a log out button in the API Center Portal? And is it possible to provide additional information, like the logged in user's display name via the portal? It's a little confusing.

<img width="1102" alt="image" src="https://github.com/Azure/api-center-preview/assets/76496924/d916e7f3-d83e-40a4-91b6-6df269f7f1e6">

**Comment by juliajuju93** [comment]
@georgeollis : 
To provide more flexibility and better control to our customers, we decommissioned the integrated managed APIC portal and instead focus on providing a reference implementation for APIC portal with one click deployment model - so customers can bring up this portal in their subscription and have more flexibility around e.g. custom domain.

Please take a look and let me know if this solution will help with your requirement: https://github.com/Azure/APICenter-Portal-Starter

thanks
