### ISSUE TITLE
Import problems

### ISSUE THREAD

**Issue by RickOttenNS** [Azure/api-center#38]
# Description

According to the [documentation](https://learn.microsoft.com/en-us/azure/api-center/key-concepts), API Centerallows any API definition file formatted as text (YAML, JSON, Markdown, and so on). You can upload OpenAPI, gRPC, GraphQL, AsyncAPI, WSDL, and WADL definitions, among others. This means [this feature request ](https://github.com/Azure/api-center-preview/issues/8) should be covered. However, it doesn't seem to be - yet.

The API types selection is an enumerated list - that doesn't contain AsyncAPI for example. Will this list be editable at a later stage? Moreover, the import cmdlet:

`Az apic api register --api-location petstore.yml`

fails on anything other than json. (And, seeing as markdown is mentioned for an import file, I would expect markdown to be honored in API descriptions in the portal as well. This is not the case. Are there plans for this?

**Comment by UniperMaster** [comment]
Agree Yaml doesnt work from me

**Comment by blackchoey** [comment]
Here's a daily build that contains the support of yaml. You can get it at https://github.com/blackchoey/azure-cli-extensions/releases/tag/20240416.

Note: it's not an official release so please expect bugs in it.

**Comment by pierceboggan** [comment]
@UniperMaster @RickOttenNS - The Azure CLI release containing this fix is now live, and I can confirm I can't reproduce this using a YAML-based specification document.

![image](https://github.com/Azure/api-center/assets/1091304/1c62bcbd-50e7-4068-b63c-69ff36a41519)

You should also be able to provide `AsyncAPI` as a valid specification name as it is a supported type. 

If you still have issues, feel free to reopen and tag us.

Thanks again for the report! :)
