### ISSUE TITLE
API version fallback on a few commands/actions

### ISSUE THREAD

**Issue by justinyoo** [Azure/api-center#45]
# Description

When I delete an APIC instance from Azure Portal or Azure CLI, it throws an error that the API version of `2024-03-15-preview` doesn't support this action. However, when I use the `az rest ...` command that uses the REST API request with the API version of `2024-03-01`, I was able to delete the APIC instance.

Would it be possible to provide a fallback API vesion to both Azure Portal and Azure CLI so that users don't get confused?

# Reproduction steps

1. Create an APIC instance
2. Delete it from Azure Portal or using Azure CLI command like `az apic delete ...`
3. See error

# Expected behavior

The APIC instance should be deleted with no issue.

# Actual behavior

The APIC instance is not deleted but throws an error with the message of "API version `2024-03-15-preview` is not supported".

# Screenshots

![image](https://github.com/Azure/api-center-preview/assets/1538528/1e87f986-a815-440a-b6f5-8e09713bf2a9)

**Comment by pierceboggan** [comment]
Spoke with @justinyoo. Confirmed this is now fixed! Thanks for the bug report :)
