### ISSUE TITLE
How to access to the API Center functionalities via API?

### ISSUE THREAD

**Issue by MassimoC** [Azure/api-center#5]
# What are you trying to achieve?

Would like to access to the API center functionalities via an API so I can integrate the API Center in my API design workflow
Will the API be available during the preview?

# Proposed solution

N/A

# Alternative solutions

N/A

# Additional context

N/A

**Comment by azaslonov** [comment]
@MassimoC, there is API that you can try out right away. It is not documented yet, but I sent you the HTTP file with all examples for all the requests. Hope that helps. Please note, that there is a chance that the API may change.

**Comment by MassimoC** [comment]
> I sent you the HTTP file with all examples

thank you @azaslonov ! Can you please send your email to massimo.crippa@codit.eu ? Thanks a lot

**Comment by rutger-buiteman** [comment]
> @MassimoC, there is API that you can try out right away. It is not documented yet, but I sent you the HTTP file with all examples for all the requests. Hope that helps. Please note, that there is a chance that the API may change.

Would it be possible to get this documentation as well?

**Comment by pierceboggan** [comment]
@MassimoC @rutger-buiteman This documentation is now available for both our resource manager and data plane APIs: https://learn.microsoft.com/en-us/rest/api/apicenter/

Let us know if there's anything we can do to improve the API. 

Thanks again for this ask!
