### ISSUE TITLE
Adding a new item to a "Predefined choices" Metadata item fails

### ISSUE THREAD

**Issue by RaynaLT** [Azure/api-center#6]
# Description

Adding a new item to a "Predefined choices" Metadata item fails with the following error: "Cannot delete, change type or unassign the "products" schema when custom properties defined for it. Delete the respective properties in all the entities before removing the the schema."

# Reproduction steps

1. Add a new Metadata schema "Predefined choices" item named "Products" and allow this to be used in "Environments"
2.  Go to an Environments item and select a choice for the metadata item "Products"
3. Go back to Metadata and attempt to add a new item to the predefined choices list
4. Get an error "Request failed": "Cannot delete, change type or unassign the "products" schema when custom properties defined for it. Delete the respective properties in all the entities before removing the the schema."

# Expected behavior

You should be able to add new items to a "Predefined choices" list in the Metadata schema area.

# Actual behavior

Editing a "Predefined choices" list by adding a new item after initial save will fail.

# Screenshots

![image](https://github.com/Azure/api-center-preview/assets/100566888/00af0aee-da8d-4722-b9aa-c38686bb9058)

# Additional context

N/A

**Comment by mikebudzynski** [comment]
@RaynaLT None of our team members could reproduce your issue. Could you retry it to see if you are still getting an error?

My attempt at reproducing the issue:

1. I created a new pre-defined choices metadata property "products" with 3 values: product1, product2, product3. I made it required for environments and not applicable for other resource types.
2. I edited one of my environments to specify "products2".
3. I edited the metadata property to include one more option product4 and saved it.
4. I edited the metadata property to remove product2 from the options and saved it.

All the operations succeeded without any errors.
