### ISSUE TITLE
Link APIs to Environments

### ISSUE THREAD

**Issue by RaynaLT** [Azure/api-center#7]
# What are you trying to achieve?

I would like to add multiple Environments and have them appear in the API setup area as a dropdown list similar to a Metadata schema "Predefined choices" list.

# Proposed solution

Treat Environment items as a special / UI-supported instance of the Metadata scheme "Predefined choices" list.

# Alternative solutions

Remove the "Environments" as a UI option if you can't link them to anything. 

# Additional context
![image](https://github.com/Azure/api-center-preview/assets/100566888/9ec77e9f-99a9-412d-9ffa-bf1ae94bfc17)

**Comment by mikebudzynski** [comment]
@RaynaLT You can link APIs to environments through API deployments. Create an API -> create an API version -> create a deployment and associate it with an environment:

![image](https://github.com/Azure/api-center-preview/assets/40186513/c161b9d3-4eb2-4b3c-bd03-405b4bd8ce62)

If this model doesn't work for you, can you explain your scenario in more detail and why you want environments to be per API and not per API deployment?

**Comment by juliajuju93** [comment]
@RaynaLT :
I would love to follow up on this threat. Would you be able to jump on a call to discuss some of your requirements. Me and the team, would love to better understand what you would want and need from the product.
Best wishes
Julia

**Comment by juliajuju93** [comment]
CLOSING

**Comment by juliajuju93** [comment]
✅
